image: golang:1.12

before_script:
  - git config --global http."https://${GITLAB_SERVER}".proxy ""
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_SERVER}".insteadOf "https://${GITLAB_SERVER}"

  - echo "[http \"https://${GITLAB_SERVER}\"]" >> ~/.gitconfig
  - echo "        proxy = \"\"" >> ~/.gitconfig
  - cd $CI_PROJECT_DIR
  - apt update -yq && apt install -yq makeself

variables:
  http_proxy: "${HTTP_PROXY}"
  https_proxy: "${HTTPS_PROXY}" 
  no_proxy: "${NO_PROXY}"
  NO_PROXY: "${NO_PROXY}"

  
stages:
 - build
 - test
 - dist
 - pages

compile:
  stage: build
  tags: 
    - go
  script:
  - go build ./...

test:
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_HOSTNAME: postgres
    POSTGRES_DB: pgdb
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: test
  tags: 
    - go
  script:
    - go test ./... -tags=integration -coverprofile cover.out
    - go tool cover -func cover.out
    - go tool cover -html=cover.out -o cover.html
  artifacts:
    paths:
      - "cover.html"

installer:
  stage: dist
  tags:
    - go
  script:
    - apt update && apt install -y makeself
    - make installer
    - cp ./doc/openapi.yml ./out/openapi.yml
    - cd dist/linux/aas-manager && make && cd -
    - cp dist/linux/aas-manager/populate-users ./out/populate-users 
    - cp dist/linux/install_pgdb.sh ./out/install_pgdb.sh
    - cp dist/linux/create_db.sh ./out/create_db.sh
  artifacts:
    paths:
      - "out/authservice-*.bin"
      - "out/openapi.yml"
      - "out/populate-users"
      - "out/install_pgdb.sh"
      - "out/create_db.sh"

docker:
  stage: dist
  tags: 
    - go
    - docker
  script:
    - curl -sSL https://get.docker.com/ | sh
    - apt-get update && apt-get install -y makeself
    - make docker
    - cp ./dist/docker/docker-compose.yml ./out/docker-compose.yml
    - cp ./doc/openapi.yml ./out/openapi.yml
  artifacts:
    paths:
      - "out/*.tar"
      - "out/docker-compose.yml"
      - "out/openapi.yml"

lld:
  stage: dist
  tags:
    - go
  script:
    - apt update && apt install -y pandoc
    - pandoc --standalone --css pandoc.css -f markdown_github -t html5 doc/LLD.md -o LLD.html
  artifacts:
    paths:
      - LLD.html

pages:
  stage: pages
  tags:
    - go
  dependencies:
    - test
    - lld
  script:
    - mkdir -p public/
    - cp cover.html public/cover.html
    - cp LLD.html public/LLD.html
  artifacts:
    paths:
    - public
  only:
  - master
